-- QUAN LY GIAO VU
-- 1) Tao quan he va khai bao tat ca cac rang buoc khoa chinh, khoa ngoai, them 3 thuoc tinh GHICHU, DIEMTB, XEPLOAI cho quan he HOCVIEN
CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA VARCHAR(40), 
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)
CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)
CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL
)
CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME, 
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
)
CREATE TABLE LOP
(
	MALOP CHAR(3) NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
)
CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
)
CREATE TABLE GIANGDAY
(
	MALOP CHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME
)
CREATE TABLE KETQUATHI
(
	MAHV CHAR(5) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LANTHI TINYINT NOT NULL,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
)
ALTER TABLE HOCVIEN 
ADD CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV);
ALTER TABLE LOP
ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP);
ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA);
ALTER TABLE MONHOC
ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH);
ALTER TABLE DIEUKIEN
ADD CONSTRAINT PK_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC);
ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV);
ALTER TABLE GIANGDAY
ADD CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH);
ALTER TABLE KETQUATHI
ADD CONSTRAINT PK_KQTHI PRIMARY KEY (MAHV, MAMH, LANTHI);

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_MALOP_HOCVIEN
FOREIGN KEY (MALOP)
REFERENCES LOP (MALOP);

ALTER TABLE LOP
ADD CONSTRAINT FK_MAGVCN_LOP
FOREIGN KEY (MAGVCN)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE KHOA
ADD CONSTRAINT FK_TRGKHOA_KHOA
FOREIGN KEY (TRGKHOA)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MAKHOA_MONHOC
FOREIGN KEY (MAKHOA)
REFERENCES KHOA (MAKHOA);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_MAMH_DIEUKIEN
FOREIGN KEY (MAMH)
REFERENCES MONHOC (MAMH);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_MAMH_TRUOC_DIEUKIEN
FOREIGN KEY (MAMH_TRUOC)
REFERENCES MONHOC (MAMH);

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_MAKHOA_GIAOVIEN
FOREIGN KEY (MAKHOA)
REFERENCES KHOA (MAKHOA);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_MALOP_GIANGDAY
FOREIGN KEY (MALOP)
REFERENCES LOP (MALOP);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_MAMH_GIANGDAY
FOREIGN KEY (MAMH)
REFERENCES MONHOC (MAMH);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_MAGV_GIANGDAY
FOREIGN KEY (MAGV)
REFERENCES GIAOVIEN (MAGV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_MAHV_KQTHI
FOREIGN KEY (MAHV)
REFERENCES HOCVIEN (MAHV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_MAMH_KQTHI
FOREIGN KEY (MAMH)
REFERENCES MONHOC (MAMH);

ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(100);
ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(3,2);
ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10);

---------------------------------------------------------------------------------------------------------
-- I.
-- 2) Ma hoc vien la 1 chuoi 5 ky tu, 3 ky tu dau la ma lop, 2 ky tu cuoi la so thu tu hoc vien trong lop
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHUANHOA_MAHV
CHECK (MAHV like '[A-Z][0-9][0-9][0-9][0-9]');
-- 3) Thuoc tinh GIOITINH chi co gia tri la "Nam" hoac "Nu"
ALTER TABLE HOCVIEN 
ADD CONSTRAINT GIOITINHHOCVIEN
CHECK (GIOITINH in ('Nam', 'Nu'));

ALTER TABLE GIAOVIEN
ADD CONSTRAINT GIOITINHGIAOVIEN
CHECK (GIOITINH in ('Nam', 'Nu'));
-- 4) Diem so cua mot lan thi co gia tri tu 0 den 10 va can luu den 2 so le
ALTER TABLE KETQUATHI
ALTER COLUMN DIEM NUMERIC(3,2);
ALTER TABLE KETQUATHI
ADD CONSTRAINT DIEUKIEN_DIEM
CHECK (DIEM >=0 AND DIEM <= 10);
-- 5) Ket qua thi la "Dat" neu diem tu 5 den 10 va "Khong dat" neu diem nho hon 5
UPDATE KETQUATHI
SET KQUA = 'Dat' WHERE (DIEM <= 10 AND DIEM >= 5);
UPDATE KETQUATHI
SET KQUA = 'Khong Dat' WHERE (DIEM <= 5 AND DIEM >= 0);
-- 6) Hoc vien thi mot mon toi da 3 lan
ALTER TABLE KETQUATHI
ADD CONSTRAINT SOLANTHI
CHECK (LANTHI >= 0 AND LANTHI <= 3);
-- 7) Hoc ky chi co gia tri tu 1 den 3
ALTER TABLE GIANGDAY
ADD CONSTRAINT DIEUKIENHOCKY
CHECK (HOCKY = 1 OR HOCKY = 2 OR HOCKY = 3);
-- 8) Hoc vi cua Giao vien chi co the la "CN", "KS", "Ths", "TS", "PTS"
ALTER TABLE GIAOVIEN
ADD CONSTRAINT DIEUKIENHOCVI
CHECK (HOCVI in ('CN','KS','Ths','TS','PTS'));

--II
--II.1: Tang he so luong them 0.2 cho nhung giao vien la truong khoa
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)
--II.3: Cap nhat gia tri cho cot GHICHU la "Cam thi" doi voi truong hop hoc vien co mot mon bat ky thi lan thu 3 duoi 5 diem
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN
(
	SELECT MAHV FROM KETQUATHI
	WHERE LANTHI = 3 AND DIEM < 5
)
--III
--III.1 In ra danh sach (ma hoc vien, ho ten, ngay sinh, ma lop) lop truong cua cac lop
SELECT MAHV, HO, TEN, NGSINH, MALOP FROM HOCVIEN
WHERE MAHV IN (SELECT TRGLOP FROM LOP)
--III.2 In ra bang diem khi thi mon CTRR cua lop "K12", sap xep theo ten, hoc hoc vien
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.LANTHI, KETQUATHI.DIEM
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE HOCVIEN.MALOP = 'K12' AND KETQUATHI.MAMH = 'CTRR'
ORDER BY HOCVIEN.TEN, HOCVIEN.HO
--III.3 In ra danh sach nhung hoc vien va nhun mo hoc ma hoc vien do thi lan thu nhat da dat
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.MAMH 
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV 
WHERE KETQUATHI.LANTHI = 1 AND KETQUATHI.KQUA = 'Dat'
--III.4 In ra danh sach hoc vien cua lop K11 thi mon CTRR khong dat o lan thi 1
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN
FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE HOCVIEN.MALOP = 'K11' AND KETQUATHI.MAMH = 'CTRR' AND KETQUATHI.KQUA = 'Khong dat' AND KETQUATHI.LANTHI = 1
-- 19. Khoa nao (Ma khoa, ten khoa) duoc thanh lap som nhat
SELECT MAKHOA, TENKHOA FROM KHOA 
WHERE NGTLAP = (SELECT MIN(NGTLAP) FROM KHOA);
-- 20. Co bao nhieu giao vien co hoc ham la 'GS' hoac 'PGS'
SELECT COUNT(MAGV) AS SoLuongGiaoVien FROM GIAOVIEN
WHERE HOCHAM = 'GS' OR HOCHAM = 'PGS';
-- 21. Thong ke co bao nhieu giao vien co hoc vi la 'CN', 'KS', 'Ths', 'TS', 'PTS' trong moi khoa
SELECT KHOA.MAKHOA, TENKHOA, GIAOVIEN.HOCVI, COUNT(*) AS SoLuongGiaoVien 
FROM GIAOVIEN INNER JOIN KHOA ON GIAOVIEN.MAKHOA = KHOA.MAKHOA
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA, GIAOVIEN.HOCVI
ORDER BY KHOA.MAKHOA
-- 22. Moi mon hoc thong ke so luong hoc vien theo ket qua (Dat va khong dat)
SELECT MONHOC.MAMH, TENMH, KQUA, COUNT(*) AS SoLuongHocVien
FROM MONHOC INNER JOIN KETQUATHI ON MONHOC.MAMH = KETQUATHI.MAMH
WHERE KQUA IN ('Dat', 'Khong dat')
GROUP BY MONHOC.MAMH, TENMH, KETQUATHI.KQUA
ORDER BY MONHOC.MAMH
-- 23. Tim giao vien la GVCN cua mot lop, dong thoi day cho lop do it nhat mot mon
SELECT DISTINCT GIAOVIEN.MAGV, HOTEN FROM GIAOVIEN
INNER JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
INNER JOIN LOP ON GIAOVIEN.MAGV = LOP.MAGVCN AND GIANGDAY.MALOP = LOP.MALOP
-- 24. Tim ho ten cua lop truong co si so cao nhat
SELECT HO, TEN FROM HOCVIEN INNER JOIN LOP ON HOCVIEN.MALOP = LOP.MALOP
WHERE HOCVIEN.MAHV = LOP.TRGLOP AND SISO = (SELECT MAX(SISO) FROM LOP)
-- 25. Tim ho ten nhung LOPTRG thi khong dat qua 3 mon (moi mon deu thi khong dat o tat ca lan thi)
SELECT HO, TEN FROM HOCVIEN INNER JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP
WHERE HOCVIEN.MAHV = LOP.TRGLOP AND NOT EXISTS (
    SELECT 1 FROM HOCVIEN WHERE HOCVIEN.MALOP = LOP.MALOP AND HOCVIEN.MAHV NOT IN (
        SELECT DISTINCT MAHV FROM KETQUATHI
        WHERE LANTHI <= 3 AND KQUA = 'Dat'
    )
)
-- 26. Tim hoc vien (MAHV, hoten) co so mon dat diem 9, 10 nhieu nhat
SELECT HOCVIEN.MAHV, HO, TEN FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV AND DIEM BETWEEN 9 AND 10
GROUP BY HOCVIEN.MAHV, HO, TEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM KETQUATHI WHERE DIEM >= 9 GROUP BY MAHV)
-- 27. Trong tung lop, tim hoc vien (MAHV, hoten) co so mon dat diem 9 10 nhieu nhat
SELECT MALOP, MAHV, HO, TEN
FROM (
    SELECT MALOP, HOCVIEN.MAHV, HO, TEN, COUNT(*) AS SoLuongDiem
    FROM HOCVIEN
    INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
    WHERE DIEM >= 9
    GROUP BY MALOP, HOCVIEN.MAHV, HO, TEN
) AS L1
WHERE NOT EXISTS (
    SELECT 1
    FROM (
        SELECT MALOP, HOCVIEN.MAHV, COUNT(*) AS SoLuongDiem
        FROM HOCVIEN
        INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
        WHERE DIEM >= 9
        GROUP BY MALOP, HOCVIEN.MAHV
    ) AS L2
    WHERE L1.MALOP = L2.MALOP AND L1.SoLuongDiem < L2.SoLuongDiem
);
-- 28. Trong tung hoc ky cua nam, moi giao vien phan cong day bao nhieu mon hoc, bao nhieu lop
SELECT GIAOVIEN.MAGV,HOTEN, HOCKY, NAM, COUNT(DISTINCT MAMH) AS SoMonHocGiangDay, COUNT(DISTINCT MALOP) AS SoLopGiangDay
FROM GIAOVIEN INNER JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
GROUP BY GIAOVIEN.MAGV, HOTEN, HOCKY, NAM
-- 29. Trong tung hoc ky cua nam, tim giao vien (MAGV, hoten) giang day nhieu nhat
SELECT GIANGDAY.MAGV, GIAOVIEN.HOTEN, GIANGDAY.HOCKY, GIANGDAY.NAM, COUNT(*) AS SoLuongLop
FROM GIANGDAY
JOIN GIAOVIEN ON GIANGDAY.MAGV = GIAOVIEN.MAGV
GROUP BY GIANGDAY.MAGV, GIAOVIEN.HOTEN, GIANGDAY.HOCKY, GIANGDAY.NAM
HAVING COUNT(*) = (
        SELECT MAX(SoLuongLop)
        FROM (
            SELECT GIANGDAY.MAGV, GIANGDAY.HOCKY, GIANGDAY.NAM, COUNT(*) AS SoLuongLop
            FROM GIANGDAY
            GROUP BY GIANGDAY.MAGV, GIANGDAY.HOCKY, GIANGDAY.NAM
        ) AS LopGiangDay
        WHERE LopGiangDay.HOCKY = GIANGDAY.HOCKY AND LopGiangDay.NAM = GIANGDAY.NAM
    )
ORDER BY GIANGDAY.HOCKY, GIANGDAY.NAM;            
-- 30. Tim mon hoc (MAMH, tenmh) co nhieu hoc vien thi khong dat (o lan thi thu nhat) nhat
SELECT MONHOC.MAMH, TENMH, COUNT(*) AS SoLuongHocVienKhongDat FROM KETQUATHI
INNER JOIN MONHOC ON KETQUATHI.MAMH = MONHOC.MAMH
WHERE LANTHI = 1 AND KQUA = 'Khong dat'
GROUP BY MONHOC.MAMH, TENMH
ORDER BY SoLuongHocVienKhongDat DESC
-- 31. Tim hoc vien (mahv, hoten) thi mon nao cung dat (chi xet o lan thi thu nhat)
SELECT DISTINCT HOCVIEN.MAHV, HO, TEN FROM HOCVIEN
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE KQUA = 'Dat' AND LANTHI = 1
AND NOT EXISTS (
    SELECT 1 FROM KETQUATHI
    WHERE KETQUATHI.MAHV = HOCVIEN.MAHV AND KQUA = 'Khong dat' AND LANTHI = 1
)
-- 32. Tim hoc vien (mahv, hoten) thi mon nao cung dat (chi xet o lan thi sau cung)
SELECT DISTINCT HOCVIEN.MAHV, HO, TEN FROM HOCVIEN
INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE NOT EXISTS (
    SELECT 1 FROM KETQUATHI
    WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI WHERE MAHV = HOCVIEN.MAHV GROUP BY MAHV) AND KQUA = 'Khong Dat' AND MAHV = HOCVIEN.MAHV
)
-- 33. Tim hoc vien (mahv, hoten) da thi tat ca cac mon deu dat (chi xet o lan thi thu 1)
SELECT MAHV, HO, TEN FROM HOCVIEN
WHERE NOT EXISTS (
    SELECT * FROM MONHOC WHERE NOT EXISTS (
        SELECT * FROM KETQUATHI
        WHERE KETQUATHI.MAMH = MONHOC.MAMH AND KETQUATHI.MAHV = HOCVIEN.MAHV AND LANTHI = 1 AND KQUA = 'Khong Dat'
    )
)
-- 34. Tim hoc vien (mahv, hoten) da thi tat ca cac mon deu dat (chi xet o lan thi cuoi cung)
SELECT MAHV, HO, TEN FROM HOCVIEN
WHERE NOT EXISTS (
    SELECT * FROM MONHOC WHERE NOT EXISTS (
        SELECT * FROM KETQUATHI
        WHERE KETQUATHI.MAMH = MONHOC.MAMH AND KETQUATHI.MAHV = HOCVIEN.MAHV 
        AND LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI WHERE MAHV = HOCVIEN.MAHV GROUP BY MAHV) AND KQUA = 'Khong Dat' and MAHV = HOCVIEN.MAHV
    )
)
-- 35. Tim hoc vien (mahv, hoten) co diem thi cao nhat trong tung mon (Lay diem o lan thi sau cung)
SELECT MAMH, MAHV, HO, TEN FROM
(
    SELECT MAMH, HOCVIEN.MAHV, HO, TEN, RANK() OVER (PARTITION BY MAMH ORDER BY MAX(DIEM) DESC) AS XEPHANG
    FROM HOCVIEN INNER JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
    WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI WHERE MAHV = HOCVIEN.MAHV GROUP BY MAHV)
    GROUP BY MAMH, HOCVIEN.MAHV, HO, TEN
) AS A
WHERE A.XEPHANG = 1


-------------------- I.9 -> I.24-----------------------
--I.9. Lop truong cua mot lop phai la hoc vien cua lop do
-- Cach 1:
CREATE TRIGGER TRG_IU_LopTruong on LOP
FOR INSERT, UPDATE
AS
BEGIN
    IF (SELECT COUNT(*) FROM INSERTED I, HOCVIEN WHERE I.TRGLOP = HV.MAHV AND I.MALOP = HV.MALOP) > 0
    BEGIN
        ROLLBACK TRANSACTION
    END
END;
GO
-- Cach 2:
CREATE TRIGGER TRG_UPT_LopTruong ON LOP
FOR INSERT, UPDATE
AS 
DECLARE 
    @MALOP_A CHAR(3), @MALOP_B CHAR(3)
    SELECT @MALOP_A = A.MALOP, @MALOP_B = B.MALOP FROM INSERTED A, HOCVIEN B WHERE A.TRGLOP = B.MAHV 
    IF (@MALOP_A <> @MALOP_B) 
    BEGIN
        ROLLBACK TRANSACTION
    END
GO
----------------------------------------------------------------------------------------------------------------------------------------------
--I.10.Truong khoa phai la giao vien thuoc khoa va co hoc vi la "TS" hoac "PTS"
CREATE TRIGGER TRG_TRGKHOA_GIAOVIEN  ON KHOA 
FOR INSERT, UPDATE
AS 
BEGIN 
    IF (SELECT COUNT(*) FROM INSERTED I INNER JOIN GIAOVIEN G on I.MAGVCN = G.MAGV WHERE I.TRGKHOA = G.TRGKHOA AND (G.HOCVI IN ('TS', 'PTS'))) = 0
    BEGIN
        ROLLBACK TRANSACTION
    END
END;
GO
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.11 Hoc vien it nhat la 18 tuoi
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHECK_TUOI_HV CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)
----------------------------------------------------------------------------------------------------------------------------------------------
--I.12 Giang day mot mon hoc ngay bat dau (TUNGAY) phai nho hon ngay ket thuc (DENNGAY)
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHECK_NGAYGIANGDAY CHECK (TUNGAY < DENNGAY)
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.13 Giao vien khi vao lam it nhat la 22 tuoi
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHECK_NGAYVL CHECK (YEAR(NGVL) - YEAR(NGSINH) >= 22)
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.14 Tat ca cac mon hoc deu co so tin chi ly thuyet va tin chi thuc hanh chenh lech nhau khong qua 3
ALTER TABLE MONHOC
ADD CONSTRAINT CHECK_TINCHI CHECK (ABS(TCLT - TCTH) <= 3)
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.15 Hoc vien chi duoc thi mot mon hoc nao do khi lop cua hoc vien da hoc xong mon hoc nay
GO
CREATE TRIGGER TRG_IU_KETQUATHI ON KETQUATHI 
FOR INSERT, UPDATE
AS 
DECLARE 
    @NGTHI SMALLDATETIME, @DENNGAY SMALLDATETIME
    SELECT @NGTHI = NGTHI, @DENNGAY = DENNGAY FROM INSERTED I, HOCVIEN H, GIANGDAY G 
    WHERE I.MAHV = H.MAHV AND H.MALOP = G.MALOP AND I.MAMH = G.MAMH
    IF (@NGTHI <= @DENNGAY)
    BEGIN
        ROLLBACK TRANSACTION 
    END
GO

CREATE TRIGGER TRG_UDT_GIANGDAY ON GIANGDAY 
FOR UPDATE
AS 
DECLARE 
    @NGTHI SMALLDATETIME, @DENNGAY SMALLDATETIME
    SELECT @DENNGAY = DENNGAY FROM INSERTED

    IF (@DENNGAY >= ALL(SELECT @NGTHI FROM INSERTED I, HOCVIEN H, GIANGDAY G WHERE I.MAHV = H.MAHV AND H.MALOP = G.MALOP AND I.MAMH = G.MAMH))
    BEGIN
        ROLLBACK TRANSACTION
    END
GO
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.16 Moi hoc ky cua mot nam hoc, mot lop chi duoc hoc toi da 3 mon
CREATE TRIGGER TRG_CHECKSOMON_16 ON LOP
AFTER INSERT, UPDATE
AS
BEGIN 
    DECLARE @MALOP CHAR(3);
    DECLARE @HOCKY INT;
    DECLARE @NAM INT;
    DECLARE @SOMONHOC INT;
    SELECT @MALOP = I.MALOP, @HOCKY = I.HOCKY, @NAM = I.NAM FROM INSERTED I;

    SELECT @SOMONHOC = COUNT(*) FROM GIANGDAY GD WHERE GD.MALOP = @MALOP AND GD.HOCKY = @HOCKY AND GD.NAM = @NAM
    IF @SOMONHOC >= 3
    BEGIN
        ROLLBACK TRANSACTION
    END
END;
GO
----------------------------------------------------------------------------------------------------------------------------------------------
-- I.17 Si so cua mot lop bang voi so luong hoc vien thuoc lop do
CREATE TRIGGER TRG_IU_SISO ON LOP 
FOR INSERT, UPDATE
AS 
BEGIN
    IF EXISTS(SELECT 1 FROM INSERTED I WHERE I.SISO <> (SELECT COUNT(*) FROM HOCVIEN WHERE HOCVIEN.MALOP = I.MALOP))
    BEGIN
        ROLLBACK;
    END
END;
GO
----------------------------------------------------------------------------------------------
-- I.18 
CREATE TRIGGER TRG_IU_DK_18 ON DIEUKIEN
FOR INSERT, UPDATE
AS
DECLARE 
    @MAMH VARCHAR(10), @MAMH_TRUOC VARCHAR(10)
    SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC FROM INSERTED
    IF (@MAMH = @MAMH_TRUOC OR @MAMH IN (SELECT MAMH_TRUOC FROM DIEUKIEN WHERE MAMH = @MAMH_TRUOC) OR @MAMH_TRUOC IN (SELECT MAMH FROM DIEUKIEN WHERE MAMH_TRUOC = @MAMH))
    BEGIN
        ROLLBACK TRANSACTION
    END
GO
----------------------------------------------------------------------
-- I.19 Cac giao vien co cung hoc vi, hoc ham, he so luong thi muc luong bang nhau
CREATE TRIGGER TRG_IU_GIAOVIEN_19 ON GIAOVIEN 
FOR INSERT, UPDATE
AS
DECLARE 
    @MUCLUONG MONEY, @MAGV CHAR(4)

    SELECT DISTINCT @MUCLUONG = G.MUCLUONG, @MAGV = I.MAGV
    FROM INSERTED I, GIAOVIEN G
    WHERE I.MAGV <> G.MAGV AND I.HOCVI = G.HOCVI AND I.HESO = G.HESO AND A.HOCHAM = B.HOCHAM

    UPDATE GIAOVIEN 
    SET MUCLUONG = @MUCLUONG WHERE MAGV = @MAGV 
GO
-----------------------------------------------------------------------------
-- I.20 Hoc vien chi duoc thi lai (lan thi > 1) khi diem cua lan thi truoc do duoi 5
CREATE TRIGGER TRG_CHECKTHILAI_20 ON KETQUATHI 
AFTER INSERT, UPDATE
AS 
BEGIN
    DECLARE @MAHV CHAR(5);
    DECLARE @MAMH VARCHAR(10);
    DECLARE @LANTHI TINYINT;
    DECLARE @DIEM NUMERIC(4, 2);
    SELECT @MAHV = I.MAHV, @MAMH = I.MAMH, @LANTHI = I.LANTHI, @DIEM = I.DIEM FROM INSERTED I;
    IF @LANTHI > 1 AND NOT EXISTS (
        SELECT 1 FROM KETQUATHI KQ WHERE KQ.MAHV = @MAHV AND KQ.MAMH = @MAMH AND KQ.LANTHI = @LANTHI - 1 AND KQ.DIEM < 5
    )
    BEGIN 
        ROLLBACK TRANSACTION
    END
END;
GO
------------------------------------------------------------------------------------------------
-- I.21 Ngay thi cua lan thi sau phai lon hon ngay thi cua lan thi truoc
CREATE TRIGGER TRG_CHECK_LANTHI_21 ON KETQUATHI 
AFTER INSERT, UPDATE
AS
BEGIN 
    DECLARE @MAHV CHAR(5);
    DECLARE @MAMH VARCHAR(10);
    DECLARE @LANTHI TINYINT;
    DECLARE @NGAYTHI SMALLDATETIME;
    SELECT @MAHV = I.MAHV, @MAMH = I.MAMH, @LANTHI = I.LANTHI, @NGAYTHI = I.NGTHI;
    IF @LANTHI > 1 AND EXISTS (
        SELECT 1 FROM KETQUATHI KQ WHERE KQ.MAHV = @MAHV AND KQ.MAMH = @MAMH AND KQ.LANTHI = @LANTHI - 1 AND KQ.NGTHI > @NGAYTHI
    )
    BEGIN
        ROLLBACK TRANSACTION
    END
END;
GO
------------------------------------------------------------------------ 
-- I.22 Hoc vien chi duoc thi nhung mon ma lop cua hoc vien do da hoc xong
CREATE TRIGGER TRG_CHECKMON_22 ON KETQUATHI
AFTER INSERT, UPDATE
AS 
BEGIN
    DECLARE @MAHV CHAR(5);
    DECLARE @MAMH VARCHAR(10);
    SELECT @MAHV = I.MAHV, @MAMH = I.MAMH FROM INSERTED I;
    IF NOT EXISTS(
        SELECT 1 FROM HOCVIEN HV
        INNER JOIN LOP L ON HV.MALOP = L.MALOP
        INNER JOIN MONHOC MH ON MH.MAMH = L.MAMH AND MH.MAMH = @MAMH
        WHERE HV.MAHV = @MAHV
    )
    BEGIN
        ROLLBACK TRANSACTION
    END
END;
GO
------------------------------------------------------------------------------------
-- I.23
-----------------------------------------------------------------------------------
-- I.24 Giao vien chi duoc phan cong day nhung mon thuoc khoa giao vien do phu trach
CREATE TRIGGER TRG_CHECK_PHANCONG ON GIANGDAY
AFTER INSERT, UPDATE
AS 
BEGIN
    DECLARE @MAGV CHAR(5);
    DECLARE @MAMH VARCHAR(10);
    SELECT @MAGV = I.MAGV, @MAMH = I.MAMH FROM INSERTED I;
    IF NOT EXISTS(
        SELECT 1 FROM GIAOVIEN GV
        INNER JOIN KHOA K ON GV.MAKHOA = K.MAKHOA
        INNER JOIN MONHOC MH ON MH.MAKHOA = K.MAKHOA AND MH.MAMH = @MAMH
        WHERE GV.MAGV = @MAGV
    )
    BEGIN
        ROLLBACK TRANSACTION
    END
END;